baseURL: "https://www.example.com/"
theme: "up-business-theme"
languageCode: "en-us"

title: "Saasi"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "SaaSi"
  description: "Package and deploy Cloud Native apps faster"
  images: 
    - "images/saasi_logo.png"
  
  postProcess: false

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "Community"
      url: "https://github.com/Cloud-Native-SaaSi"
      weight: 2

    - name: "Contribute"
      url: "/#"
      weight: 3

    - name: "Documents"
      url: "/#"
      weight: 4


  buttons:
    - name: "Get stated"
      url: "/#"
      weight: 5
      pre: "btn btn-primary text-light"


taxonomies:
  series: "series"
  tags: "tags"
